# Generated by Django 5.2.4 on 2025-07-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_groups', '0002_hobbygroup_banner_url'),
        ('posts', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='hobby_groups.hobbygroup'),
            preserve_default=False,
        ),
    ]
