# Generated by Django 5.2.4 on 2025-07-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(default=4),
            preserve_default=False,
        ),
    ]
