# Generated by Django 5.2.4 on 2025-07-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbygroup',
            name='banner_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
